### ISSUE TITLE
เสนอความคิดเห็นโครงงาน

### ISSUE THREAD

**Issue by ppetes** [ppetes/-scratch-2#1]

**Comment by ppetes** [comment]
เราจะทำเกมแนวไหนดี

**Comment by poonbcw** [comment]
> เราจะทำเกมแนวไหนดี

ทำเป็น 2d มั้ย

**Comment by ppetes** [comment]
> > เราจะทำเกมแนวไหนดี
> 
> ทำเป็น 2d มั้ย

ได้ๆเอาเป็นด่านสัก10ด่านมั้ย

**Comment by poonbcw** [comment]
> > > เราจะทำเกมแนวไหนดี
> > 
> > 
> > ทำเป็น 2d มั้ย
> 
> ได้ๆเอาเป็นด่านสัก10ด่านมั้ย

โอเคเลย เดี๋ยวลองร่างฉากแปป

**Comment by poonbcw** [comment]
เอาเกมชื่อไรดี

**Comment by ppetes** [comment]
https://scratch.mit.edu/projects/722821287/editor/

**Comment by AutsadaWiriya** [comment]
อยากได้เกมแบบเดิม แต่สู้โควิด ลักษณะต่างๆ(หน้าตาโควิดจะโหดขึ้นในแต่ละด่าน) แล้วก็มียาให้เก็บด้วยเพิ่มเลือด มีเข็มฉีดยาเพื่อป้องกันการโจมตีของโควิดในระยะเวลาหนึ่ง

**Comment by AutsadaWiriya** [comment]
https://scratch.mit.edu/projects/728758266

**Comment by ppetes** [comment]
เราจะยังเอารางวัลที่ผ่านครบ2ด่านอยู่อีกป่ะ

**Comment by AutsadaWiriya** [comment]
> เราจะยังเอารางวัลที่ผ่านครบ2ด่านอยู่อีกป่ะ

ยังไงอะ ถ้าครบ2ด่าน จะได้รางวัลแบบไหนอะ

**Comment by ppetes** [comment]
ไม่ต้องมีแล้วก็ได้ๆ

**Comment by ppetes** [comment]
เราเอาแบบให้มีกำหนดเวลาในแต่ละด่านละดูมั้ยมันจะได้ดูยากขึ้นอ่ะ @AutsadaWiriya

**Comment by ppetes** [comment]
1.เพิ่มเวลาในแต่ละด่าน
2.ลดคูลดาวน์เวลาพุ่งเหลือ 2.5 วิ
3.เพิ่มหัวใจ
4.เพิ่มดาเมจดาบ
