### ISSUE TITLE
ออกแบบโค้ดการเดินของศัตรู

### ISSUE THREAD

**Issue by ppetes** [ppetes/-scratch-2#10]

**Comment by AutsadaWiriya** [comment]
การเดินของศัตรูมันบัคอะ ทำยังไงให้ไม่บัคอะ

**Comment by poonbcw** [comment]
มันเป็นอะไรนะ

**Comment by AutsadaWiriya** [comment]
บางครั้งมันเคลื่อนที่บนพื้น และมันก็ทะลุพื้นอะ

**Comment by poonbcw** [comment]
ถ้างั้นเราเปลี่ยนให้มันเคลื่อนที่ทะลุพื้นไปเลยมั้ย

**Comment by AutsadaWiriya** [comment]
โอเคค

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/190894350-dc02ca77-7696-4b77-b0c6-16c7ffa22707.png)
