### ISSUE TITLE
ออกแบบไอเทม

### ISSUE THREAD

**Issue by poonbcw** [ppetes/-scratch-2#11]

**Comment by AutsadaWiriya** [comment]
เอายาหน้าตาแบบนี้มั้ยอะ หรือทำเป็นขวดดีอะ
![41EFA889-374D-4193-AC0E-087040CF9C0A](https://user-images.githubusercontent.com/110957364/189395025-e69394c1-285b-4040-a39d-56fe164de511.png)

**Comment by poonbcw** [comment]
ได้นะ👌🏻

**Comment by AutsadaWiriya** [comment]
ได้มั้ยๆ
![S__3923970](https://user-images.githubusercontent.com/110957364/189466616-909299db-6ff1-4be5-9426-83c140f54057.png)

**Comment by AutsadaWiriya** [comment]
![20220913_060654134_iOS](https://user-images.githubusercontent.com/110957364/189823979-14aca930-03e5-4944-8a86-ed774f94f6cc.png)
![20220913_060550848_iOS](https://user-images.githubusercontent.com/110957364/189823989-b696d867-2f2b-4347-9ec9-06ffcc33b268.png)
![20220913_060507494_iOS](https://user-images.githubusercontent.com/110957364/189824001-87a46f82-2e62-4b20-bf4f-effaa9a01c87.png)
![20220913_060038758_iOS](https://user-images.githubusercontent.com/110957364/189824010-73fe2fdf-76a3-4388-9c99-3083c8f86b67.png)
![20220913_060752777_iOS](https://user-images.githubusercontent.com/110957364/189824016-46809c10-8a71-4d65-87bf-2b298791ce2f.png)
![20220913_060835519_iOS](https://user-images.githubusercontent.com/110957364/189824024-8d2af535-0339-48fd-909f-21e6fd9e88f9.png)
![20220913_060918730_iOS](https://user-images.githubusercontent.com/110957364/189824031-71db12f2-0b3a-41c8-b275-550a4248849a.png)

**Comment by poonbcw** [comment]
หน้าของรางวัลนี่คือยังไงนะเป็นแบบจอดำละมีการ์ดให้เลือกงี้หรอ

**Comment by ppetes** [comment]
ใช่ๆ

**Comment by poonbcw** [comment]
ละแบบจะมีการ์ดกี่ใบอะ

**Comment by ppetes** [comment]
2 ใบ

**Comment by poonbcw** [comment]
![card1](https://user-images.githubusercontent.com/110962501/190844674-5dba9de9-d925-4ff8-9846-eb0d8640e62f.png)
![card2](https://user-images.githubusercontent.com/110962501/190844677-1ab2ad24-77e4-4452-890f-f18ec6683485.png)

**Comment by poonbcw** [comment]
ไอเทมนี่จะเอาไรเพิ่มอีกปะ หรือเอาแค่เข็มฉีดยากับย่เท่าที่มี

**Comment by AutsadaWiriya** [comment]
> ไอเทมนี่จะเอาไรเพิ่มอีกปะ หรือเอาแค่เข็มฉีดยากับย่เท่าที่มี

เอาเท่านี้มั้ย 
ยา(เพิ่มเลือด)
เข็ม(อมตะ 10วิ)

**Comment by poonbcw** [comment]
เคคคค
