### ISSUE TITLE
ทดสอบความสนุกของเกมและปัญหาต่างๆ

### ISSUE THREAD

**Issue by ppetes** [ppetes/-scratch-2#12]

**Comment by AutsadaWiriya** [comment]
https://scratch.mit.edu/projects/728758266

**Comment by ppetes** [comment]
ตอนหัวใจหมดมันไม่จบเกมให้อ่ะ ลองแก้ดูๆ @AutsadaWiriya

**Comment by AutsadaWiriya** [comment]
เมื่อกี้เอาโค้ดออก จะลองทำอย่างอื่นดู

**Comment by AutsadaWiriya** [comment]
กำลังลองทำอะไรตอนมันตายดูอะ

**Comment by AutsadaWiriya** [comment]
เอาด่านแต่ละด่านกี่วินาทีอะ

**Comment by ppetes** [comment]
ต้องลองเล่นดูก่อนอ่ะ

**Comment by ppetes** [comment]
มันกดตีค้างได้อ่ะ แล้วก็พอผ่าน2ด่านแล้วมันต้องเป็นหน้าสีดำเฉยๆให้เลือกการ์ดกก่อนแล้วค่อยไปด่านต่อไป
แล้วส่วนเรื่องเวลาคือเป็นเวลาของแต่ละด่านนะไม่ใช่้วลาทั้งหมดหรือว่าจะให้เป็นเวลาทั้งหมดอ่ะ

**Comment by AutsadaWiriya** [comment]
> มันกดตีค้างได้อ่ะ แล้วก็พอผ่าน2ด่านแล้วมันต้องเป็นหน้าสีดำเฉยๆให้เลือกการ์ดกก่อนแล้วค่อยไปด่านต่อไป แล้วส่วนเรื่องเวลาคือเป็นเวลาของแต่ละด่านนะไม่ใช่้วลาทั้งหมดหรือว่าจะให้เป็นเวลาทั้งหมดอ่ะ

ไม่ได้ใส่ดีเลย์ละอะ

**Comment by AutsadaWiriya** [comment]
เวลายังทำไม่เสร็จเลย

**Comment by ppetes** [comment]
ลอง

> > มันกดตีค้างได้อ่ะ แล้วก็พอผ่าน2ด่านแล้วมันต้องเป็นหน้าสีดำเฉยๆให้เลือกการ์ดกก่อนแล้วค่อยไปด่านต่อไป แล้วส่วนเรื่องเวลาคือเป็นเวลาของแต่ละด่านนะไม่ใช่้วลาทั้งหมดหรือว่าจะให้เป็นเวลาทั้งหมดอ่ะ
> 
> ไม่ได้ใส่ดีเลย์ละอะ

ลองใส่ดีเลย์ดูอ่ะสัก0.5วิก็ได้ลองๆปรับดูเพราะมันงั้นมันแค่กดค้างก็ผ่านละอ่ะ

**Comment by ppetes** [comment]
อ่าเคๆ

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/190905097-adc5e85e-7aae-4840-bbb2-23278560e45b.png)

**Comment by ppetes** [comment]
map 1 มี 2 ตัว
map 2,3 มี 3 ตัว
map 4,5,6 มี 4 ตัว
map 7,8  มี 5 ตัว

**Comment by ppetes** [comment]
ดาเมจเท่าไหร่นะตอนตีอ่ะ

**Comment by ppetes** [comment]
ลืมอ่านข้างล่าง555555

**Comment by AutsadaWiriya** [comment]
ดาเมจ 10

**Comment by ppetes** [comment]
map 2,4 เลือด 20
map3,5,7 เลือด30
map 6,8 เลือด 40 ประมาณนี้มั้ยคิดว่าไง

**Comment by AutsadaWiriya** [comment]
เอาเป็นตัวละครดีกว่า ตัวละครตัวนี้เลือดเท่าไหร่ แบบนี้

**Comment by ppetes** [comment]
คือจะให้แต่ละตัวเลือดต่างกันใข่มั้ย

**Comment by AutsadaWiriya** [comment]
ใช่

**Comment by ppetes** [comment]
อันนี้คิดยากเลย

**Comment by AutsadaWiriya** [comment]
> มันกดตีค้างได้อ่ะ แล้วก็พอผ่าน2ด่านแล้วมันต้องเป็นหน้าสีดำเฉยๆให้เลือกการ์ดกก่อนแล้วค่อยไปด่านต่อไป แล้วส่วนเรื่องเวลาคือเป็นเวลาของแต่ละด่านนะไม่ใช่้วลาทั้งหมดหรือว่าจะให้เป็นเวลาทั้งหมดอ่ะ

ตัวละครหายระหว่างเกม คือ GameOver เลยอะ

**Comment by ppetes** [comment]
คือยังไงอ่ะ มันหายได้ไง

**Comment by AutsadaWiriya** [comment]
ได้ละๆ

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/190911641-d68ef646-1c15-434c-bf5e-e98aa2810545.png)
เอาไพ่ตัวนี้ออกนะ

**Comment by ppetes** [comment]
ได้ๆ

**Comment by ppetes** [comment]
การ์ดเราจะมีทุกกี่ด่านนะ

**Comment by AutsadaWiriya** [comment]
เว้นด่านมั้ย

**Comment by ppetes** [comment]
ผ่าน3ด่านแล้วค่อยมีมั้ย

**Comment by ppetes** [comment]
หรือว่ายังไงอ่ะ

**Comment by AutsadaWiriya** [comment]
> ผ่าน3ด่านแล้วค่อยมีมั้ย

ใช่ๆๆๆ

**Comment by ppetes** [comment]
ได้ๆ

**Comment by ppetes** [comment]
เกมแม่งยากจังวะ55555555

**Comment by ppetes** [comment]
เลือดด่านมอนแม่งเยอะจัด

**Comment by AutsadaWiriya** [comment]
> เลือดด่านมอนแม่งเยอะจัด

เลือดไม่เยอะ แค่ยังไม่ได้กำหนดให้ตีเข้า5555

**Comment by ppetes** [comment]
ก็ว่าตียังไงก็ไม่ตาย55555

**Comment by AutsadaWiriya** [comment]
จะจบยังไงดีอะ

**Comment by poonbcw** [comment]
พอจบด่าน 8 ก็ขึ้นwin ไปเลยมะ

**Comment by AutsadaWiriya** [comment]
โอเคคค

**Comment by AutsadaWiriya** [comment]
เกมใกล้เสร็จละ ลองเล่นดูว่าจับเวลากี่นาทีดีหน่อย

**Comment by ppetes** [comment]
หน้าเลือกการ์ดทำไมมันเดินได้อ่ะ

**Comment by AutsadaWiriya** [comment]
เลือกการ์ดอันที่เท่าไหร่อะ

**Comment by ppetes** [comment]
อันที่ 1 เลย คือถ้าเราไม่เลือกแล้วลองเดินดูมันเดินได้อ่ะ

**Comment by ppetes** [comment]
![image](https://user-images.githubusercontent.com/110958597/191161060-91d34443-bf20-43e3-bde0-e653e70e28cc.png)

**Comment by ppetes** [comment]
เก็บไมไ่ด้

**Comment by ppetes** [comment]
![image](https://user-images.githubusercontent.com/110958597/191161214-f17e9843-673a-41a0-a3ef-ccc33ad37d62.png)
ไม่มีมอนเตอร์แล้วบ้างที่มันผ่านไปด่านต่อไปไม่ได้

**Comment by AutsadaWiriya** [comment]
เวลาเหลือใช่มั้ย 2นาที มาถึงด่านสุดท้ายได้เลย

**Comment by ppetes** [comment]
> เวลาเหลือใช่มั้ย 2นาที มาถึงด่านสุดท้ายได้เลย
ก็เวลามันรีเซต2นาทีทุกด่านไม่ช่ะ

**Comment by AutsadaWiriya** [comment]
ใช่ๆๆๆ

**Comment by ppetes** [comment]
เหลือๆ

**Comment by AutsadaWiriya** [comment]
แก้หมดละๆ

**Comment by ppetes** [comment]
เวลาน่าจะสัก1นาทีครึ่งพอแล้วมั้ง 2นาทีมันดูเยอะไปอ่ะ

**Comment by ppetes** [comment]
คือมีเลือกรางวัลด่านที่ 3 กับ 5 ใช่มั้ย

**Comment by AutsadaWiriya** [comment]
เอาเพิ่มไว้ด่านสุดท่ายอีกมั้ยอะ

**Comment by ppetes** [comment]
เพิ่มด่านที่ 7 ด้วยก็ได้ ด่านสุดท้ายแม่งยาก

**Comment by AutsadaWiriya** [comment]
โอเคค

**Comment by ppetes** [comment]
นอกนั้นก็ไม่น่ามีอะไรแล้วป่ะ ลองเล่นดูๆ

**Comment by AutsadaWiriya** [comment]
ลองเล่นๆ ตอนนี้น่าจะเสร็จละ

**Comment by AutsadaWiriya** [comment]
ถ้าได้แล้ว ปิดissue หมดเลยนะ
