### ISSUE TITLE
ออกแบบของรางวัล

### ISSUE THREAD

**Issue by poonbcw** [ppetes/-scratch-2#15]
มีรางวัลอะไรบ้างนะ

**Comment by poonbcw** [comment]
![card1](https://user-images.githubusercontent.com/110962501/190845009-fa4d7355-3db9-4059-95dc-288bcd7c8022.png)
![card2](https://user-images.githubusercontent.com/110962501/190845011-fec7a1a6-30a4-4a77-9223-2a2273f456b8.png)

**Comment by ppetes** [comment]
1.เพิ่มเวลาในแต่ละด่าน
2.ลดคูลดาวน์เวลาพุ่งเหลือ 2.5 วิ
3.เพิ่มหัวใจ
4.เพิ่มดาเมจดาบ
ประมาณนี้

**Comment by poonbcw** [comment]
![time(+10)](https://user-images.githubusercontent.com/110962501/190845692-3e01580a-2e34-4a6b-813f-4e34ee5795d0.png)
น่าเกลียดไปปะ คิดไม่ออกจริงๆ555555555

**Comment by poonbcw** [comment]
![heart(+1)](https://user-images.githubusercontent.com/110962501/190846031-bafd82eb-b502-4364-8bcf-c1e64e2e9a68.png)

**Comment by poonbcw** [comment]
![sword](https://user-images.githubusercontent.com/110962501/190846478-2abc4da8-d39b-4b7c-a6fd-f2f34ac27a6a.png)

**Comment by ppetes** [comment]
ได้นะเราว่า5555

**Comment by poonbcw** [comment]
![attack](https://user-images.githubusercontent.com/110962501/190888418-2accf091-d40e-4dd6-a729-5c324cadca6c.png)
