### ISSUE TITLE
ออกแบบปุ่มเมนู

### ISSUE THREAD

**Issue by poonbcw** [ppetes/-scratch-2#16]
![start](https://user-images.githubusercontent.com/110962501/190888626-3accba12-1816-4ab0-abb0-38dd6e431255.png)
![try again](https://user-images.githubusercontent.com/110962501/190888823-0afdf0f8-041c-42b2-918a-88f42c189522.png)

**Comment by poonbcw** [comment]
![game over](https://user-images.githubusercontent.com/110962501/190889202-37c6fe26-1251-4eaa-abb4-359b00cc89ec.png)

**Comment by poonbcw** [comment]
เอาคำว่าไรอีกปะ

**Comment by AutsadaWiriya** [comment]
ขอนับเวลาๆ

**Comment by poonbcw** [comment]
เอากี่นาทีนะ

**Comment by poonbcw** [comment]
หรือให้ทำเลข 0-9 ละจะไปจัดวางเอง

**Comment by AutsadaWiriya** [comment]
> หรือให้ทำเลข 0-9 ละจะไปจัดวางเอง

เอาแบบนี้ดีกว่า ง่ายดี

**Comment by poonbcw** [comment]
โอเคเลย

**Comment by poonbcw** [comment]
![3](https://user-images.githubusercontent.com/110962501/190897349-304c81bd-20d1-4bd9-bab9-f2f644a9b6c3.png)
![4](https://user-images.githubusercontent.com/110962501/190897351-eff83e62-db32-4aae-ade9-bfe9274732c5.png)
![5](https://user-images.githubusercontent.com/110962501/190897352-380fb6e9-bae7-4a35-ab63-8bd2bad61c58.png)
![6](https://user-images.githubusercontent.com/110962501/190897354-c1d3dda9-a529-4869-ae17-06944410472d.png)
![7](https://user-images.githubusercontent.com/110962501/190897356-6fddb9bf-ef95-4a4c-82bd-681af8585cf0.png)
![8](https://user-images.githubusercontent.com/110962501/190897357-c48bd041-130c-49a5-b80c-eaf44775425a.png)
![9](https://user-images.githubusercontent.com/110962501/190897359-f7a94bed-3ec2-4742-a813-3dfe59de4ec3.png)
![0](https://user-images.githubusercontent.com/110962501/190897360-1833264d-ca91-41fc-b5fa-172f376f4605.png)
![1](https://user-images.githubusercontent.com/110962501/190897361-03692e79-3ba8-410a-bf60-05ea9208f280.png)
![2](https://user-images.githubusercontent.com/110962501/190897362-1006f089-cae9-4472-bf3a-e5fee53fd8a4.png)

**Comment by poonbcw** [comment]
![00](https://user-images.githubusercontent.com/110962501/190897407-a978dd2d-2b4f-4efe-a076-3232737ba9e4.png)

**Comment by poonbcw** [comment]
![win](https://user-images.githubusercontent.com/110962501/191071780-216648d9-4927-4b3d-9ae3-75ac52f3bcf4.png)
