### ISSUE TITLE
เสียงภายในเกม

### ISSUE THREAD

**Issue by AutsadaWiriya** [ppetes/-scratch-2#17]

**Comment by poonbcw** [comment]
https://youtu.be/EMYOiK_iQeY
แบบนี้ใช้ได้มั้ย หรือต้องโหลดแบบ mp3 มา

**Comment by AutsadaWiriya** [comment]
ได้ๆๆๆๆ

**Comment by AutsadaWiriya** [comment]
link แหละ

**Comment by AutsadaWiriya** [comment]
เสียงแต่ละตัวจะเอาเสียงยังไงอะ

**Comment by ppetes** [comment]
เลือกเลยๆ

**Comment by poonbcw** [comment]
https://youtu.be/pAvGxLjogRA (เสียงพื้นหลัง)
https://youtu.be/B14L61fYZlc (เสียงเก็บไอเทม)
https://youtu.be/bug1b0fQS8Y (game over)
https://youtu.be/MH6M21jtX_k (โจมตี)

**Comment by poonbcw** [comment]
เพื่อนว่าไงกัน

**Comment by poonbcw** [comment]
https://youtu.be/-GPuzjwbkdM 
เสียงไวรัสใช้จากคลิปนี้มั้ยเอาไปตัดใช้เป็นช่วงๆไป??????
https://youtu.be/JQGT-1TJuYE (เสียงพุ่ง)

**Comment by poonbcw** [comment]
https://youtu.be/T9N0pmLI7Jw (เสียงตอนกดไพ่)
https://youtu.be/gFEbM-8Ypj0 (เสียงกดปุ่ม start / play again)

**Comment by ppetes** [comment]
ได้นะ

**Comment by poonbcw** [comment]
ต้องมีเสียงไรอีกมั้ยนะนึกไม่ออก

**Comment by AutsadaWiriya** [comment]
> 

ได้

**Comment by AutsadaWiriya** [comment]
เสียงกระโดดมั้ย
เสียงเดินด้วย

**Comment by poonbcw** [comment]
https://youtu.be/BqxWMwAjmfY (เสียงเดิน) 

https://youtu.be/BT0C7ZI2m7Y (กระโดด)
