### ISSUE TITLE
ออกแบบโค้ดที่ใช้สำหรับการเคลื่อนที่ของตัวละคร

### ISSUE THREAD

**Issue by poonbcw** [ppetes/-scratch-2#5]

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/188883396-6dfc23ec-c553-40ed-867f-f7e7715fac1e.png)

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/188896744-ca13cbae-7301-499a-9d08-e25c4869e6a6.png)

**Comment by AutsadaWiriya** [comment]
[![github](https://img.shields.io/badge/AUTSADAWIRIYA-12100E.svg?style=for-the-badge&logo=github&logoColor=white)](https://github.com/AutsadaWiriya)

![image](https://user-images.githubusercontent.com/110957364/188897684-1b6d505b-bbc3-4fa0-8339-c114a299ee0c.png)

![image](https://user-images.githubusercontent.com/110957364/188897577-5015c51f-3d78-4e32-8d3e-e91999e5ea86.png)

![image](https://user-images.githubusercontent.com/110957364/188897795-97043f2a-e095-45f3-a347-92bb2d3dce97.png)

![image](https://user-images.githubusercontent.com/110957364/188897831-06c81f48-7cb7-45f2-b7c5-42a5e11c36e3.png)

![image](https://user-images.githubusercontent.com/110957364/188898074-b261084c-e26b-4d60-9379-381a1a76645f.png)

![image](https://user-images.githubusercontent.com/110957364/188900946-9e2bce97-56f1-45d5-8791-6fc3c337f793.png)

![image](https://user-images.githubusercontent.com/110957364/188898223-de2113e0-a802-4b91-a711-15d1e05fdc42.png)

**Comment by AutsadaWiriya** [comment]
Edit
![image](https://user-images.githubusercontent.com/110957364/189386055-450ca8d7-1267-413d-be86-8e54f3c5493f.png)
