### ISSUE TITLE
ออกแบบฉาก

### ISSUE THREAD

**Issue by ppetes** [ppetes/-scratch-2#6]

**Comment by AutsadaWiriya** [comment]
ขอพื้นกับ ฉากหลังหน่อยครับ

**Comment by ppetes** [comment]
กำลังทำอยู่จ้าา ไปทำพวกการเดินของไวรัสรอก็ได้

**Comment by poonbcw** [comment]
![Sprite-0001](https://user-images.githubusercontent.com/110962501/189691685-fcdba7de-cccb-4be0-a409-256206a4a4ac.jpeg)

**Comment by poonbcw** [comment]
@AutsadaWiriya เขียนโค้ดให้แบบมันเดินแค่บนพื้นที่มีขอบขาวได้ปะ

**Comment by poonbcw** [comment]
อยากให้แก้ไรก็บอกได้นะ

**Comment by AutsadaWiriya** [comment]
ขอแยกตัวฐานกับพื้นหลังได้มั้ยอะ

**Comment by poonbcw** [comment]
![Sprite-0001](https://user-images.githubusercontent.com/110962501/189693318-b3250448-c888-475b-bc93-b8412eab8a36.jpeg)

**Comment by poonbcw** [comment]
![Sprite-0001](https://user-images.githubusercontent.com/110962501/189693395-a7cc57a6-9fbb-405c-a39a-74ec89cc0989.jpeg)

**Comment by poonbcw** [comment]
งี้หรอ

**Comment by AutsadaWiriya** [comment]
แบบข้างหลังใส PNG

**Comment by poonbcw** [comment]
![Sprite-0001](https://user-images.githubusercontent.com/110962501/189694143-0c482ae4-d062-4c94-aa06-13dbc1b4ce1a.png)

**Comment by poonbcw** [comment]
โอเคมะ

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/189699835-f66916f2-8808-41af-88c9-cc3c6d287091.png)

**Comment by AutsadaWiriya** [comment]
> ![image](https://user-images.githubusercontent.com/110957364/189699835-f66916f2-8808-41af-88c9-cc3c6d287091.png)

ชอเพิ่มระยะห่าง แกนy ของ 4ตัวนี้หน่อยครับ

**Comment by poonbcw** [comment]
![Sprite-0001](https://user-images.githubusercontent.com/110962501/189701894-12a97eb9-f521-4e0a-8af3-df7f09cd2eae.png)
เปลี่ยนเป็นแบบนี้พอได้มั้ย

**Comment by poonbcw** [comment]
![Sprite-0001](https://user-images.githubusercontent.com/110962501/189704224-0a9a06a2-975a-41cb-905a-87623427c4d1.png)

**Comment by AutsadaWiriya** [comment]
โอเคค ได้ละะ

**Comment by poonbcw** [comment]
พื้นหลังนี่อาจจะไปแก้เรื่องสีอีกภายหลังนะ แต่ตัวพื้นนี่โอเคละไม่แก้ไรแล้ว

**Comment by poonbcw** [comment]
![Sprite-0002](https://user-images.githubusercontent.com/110962501/189837662-92f78669-293f-4cc3-a017-954448f1f653.png)

**Comment by poonbcw** [comment]
![Sprite-0002](https://user-images.githubusercontent.com/110962501/189837777-07f5c3c3-24d5-43b3-a459-3a16b61eec71.png)

**Comment by poonbcw** [comment]
![Sprite-0003](https://user-images.githubusercontent.com/110962501/189928722-7b34a065-afff-4d6c-8e7e-f49666dfe7d0.png)
![Sprite-0003](https://user-images.githubusercontent.com/110962501/189929547-ecdf3f22-96eb-405b-bb9f-605f4ccc3ec8.png)

**Comment by poonbcw** [comment]
อันข้างบนเผลอทำพื้นข้างล่างสุดผิดเวลาเอาไปใช้ก็วางทับกันไปเลยนะ (โทดที)

**Comment by poonbcw** [comment]
![Sprite-0004](https://user-images.githubusercontent.com/110962501/190668617-58ca797c-815f-4543-a008-18703357e335.png)
![Sprite-0004](https://user-images.githubusercontent.com/110962501/190668688-0d4924a1-2cda-4e8e-a9db-b20f302aa443.png)

**Comment by AutsadaWiriya** [comment]
<h1 align="Center">ตัวละครติดตรงนี้ครับ</h1>

![Untitled (Draft)-1](https://user-images.githubusercontent.com/110957364/190687978-29f6dec0-fb03-46a0-8e65-b8a648d3d8f7.jpg)

**Comment by poonbcw** [comment]
![Sprite-0004](https://user-images.githubusercontent.com/110962501/190839764-3c8af90f-a2d6-40c5-9e31-fb6a17e5c7b4.png)

**Comment by poonbcw** [comment]
![Sprite-0005](https://user-images.githubusercontent.com/110962501/190841009-b1be6d9c-6dc7-47d0-ab0e-570a8718ebc7.png)
![Sprite-0005](https://user-images.githubusercontent.com/110962501/190841017-cccd85e7-9adf-435e-abfe-f6d8af6d2d07.png)

**Comment by poonbcw** [comment]
![Sprite-0006](https://user-images.githubusercontent.com/110962501/190843305-b8837ae9-2300-46b3-a148-54cdcf666263.png)
![Sprite-0006](https://user-images.githubusercontent.com/110962501/190843312-38aa8df4-d63b-4a83-a5a5-3fb6e372a43e.png)

**Comment by AutsadaWiriya** [comment]
มีฉากเท่านี้ใช่มั้ยอะ

**Comment by poonbcw** [comment]
เหลืออีก2ฉากอะ

**Comment by AutsadaWiriya** [comment]
ขอฉากแรกสุด เป็นพื้นเปล่าๆโล่งๆได้มั้ยอะ มีแค่พื้นกับพื้นหลัง

**Comment by poonbcw** [comment]
> ขอฉากแรกสุด เป็นพื้นเปล่าๆโล่งๆได้มั้ยอะ มีแค่พื้นกับพื้นหลัง

คือยังไงนะ

**Comment by poonbcw** [comment]
![Sprite-0007](https://us
![Sprite-0007](https://user-images.githubusercontent.com/110962501/191035413-e8876124-31bb-44ee-be5b-9d2954739638.png)
er-images.githubusercontent.com/110962501/191035325-0adc56ef-df92-40eb-a140-b106b7d21714.png)

**Comment by poonbcw** [comment]
![Sprite-0007](https://user-images.githubusercontent.com/110962501/191035468-a29f90ed-e2de-4f68-a6ba-135caa4b0714.png)
![Sprite-0007](https://user-images.githubusercontent.com/110962501/191035556-11fdd678-eb76-4aa9-a61a-7348a1a498cb.png)

**Comment by AutsadaWiriya** [comment]
> > ขอฉากแรกสุด เป็นพื้นเปล่าๆโล่งๆได้มั้ยอะ มีแค่พื้นกับพื้นหลัง
> 
> คือยังไงนะ
<h1 align="center"> โล่งๆแบบนี้เลย  </h1>

![image](https://user-images.githubusercontent.com/110957364/191036659-caa5ff9c-4bcc-43de-9823-486d114e5122.png)

**Comment by poonbcw** [comment]
> ![Sprite-0001](https://user-images.githubusercontent.com/110962501/189693395-a7cc57a6-9fbb-405c-a39a-74ec89cc0989.jpeg)

แบบนี้?

**Comment by AutsadaWiriya** [comment]
แบบพื้นเรียบๆ แบบนี้

**Comment by poonbcw** [comment]
![Sprite-0000](https://user-images.githubusercontent.com/110962501/191043018-7b3e8dcc-e278-45f7-8846-3e99fcf47fda.png)
เอาแค่ประมาณนี้ได้ปะ ให้ผู้เล่นลองกดกระโดด พุ่งไรงี้

**Comment by poonbcw** [comment]
หรือจะให้เขียนคำอธิบายด้วยตรงข้างบนโล่งๆว่าปุ่มไหนทำอะไร (เช่น w กระโดด )

**Comment by AutsadaWiriya** [comment]
ได้ๆๆๆ 
(เขียนเอาใส่ในพื้นหลังนะ)
//โปรดเปลี่ยนแป้นพิมพ์เป็นภาษาอังกฤษก่อนเล่น//
Space Bar : กระโดด
A : เคลื่อนที่ซ้าย                        ยา : เพิ่ม 1 ชีวิต
D : เคลื่อนที่ขวา                        วัคซีน : อมตะ 10 วิ
L : พุ่งไปข้างหน้า
K : โจมตี

**Comment by poonbcw** [comment]
![Sprite-0000](https://user-images.githubusercontent.com/110962501/191052893-6f632122-e99e-48e6-8155-3cfb7f9ba786.png)
![Sprite-0000](https://user-images.githubusercontent.com/110962501/191052962-5ed480f7-1c28-47ed-bcc3-40abfa03155c.png)

**Comment by poonbcw** [comment]
![Sprite-0000](https://user-images.githubusercontent.com/110962501/191053098-b0517e3a-c1f2-4155-9402-3ec655c2a596.png)
![Sprite-0000](https://user-images.githubusercontent.com/110962501/191053159-720ce9d5-3ebe-4890-ad33-f98ca8ddccf1.png)

**Comment by poonbcw** [comment]
ได้มั้ยๆ

**Comment by AutsadaWiriya** [comment]
ได้ๆๆๆๆๆ

**Comment by AutsadaWiriya** [comment]
ฉากหมดละใช่มั้ยอะ

**Comment by poonbcw** [comment]
![Sprite-0008](https://user-images.githubusercontent.com/110962501/191069126-f37c335e-979c-4270-b72b-0f5fbde1f0a2.png)
![Sprite-0008](https://user-images.githubusercontent.com/110962501/191069186-d660af7c-4b43-4baa-88bc-8d24ee419020.png)

**Comment by poonbcw** [comment]
หมดแล้วววววววววววววว

**Comment by AutsadaWiriya** [comment]
เย้้้
