### ISSUE TITLE
ออกแบบตัวละคร

### ISSUE THREAD

**Issue by poonbcw** [ppetes/-scratch-2#7]

**Comment by poonbcw** [comment]
[CharacterSpriteSheet.zip](https://github.com/ppetes/project-scratch-2/files/9536106/CharacterSpriteSheet.zip)

**Comment by AutsadaWiriya** [comment]
ทำยังไงให้โหลดไวๆอะ5555
![image](https://user-images.githubusercontent.com/110957364/189371381-ce03f47e-a425-4e3a-b31b-964509edf4ad.png)

ปรับสุดละ

![image](https://user-images.githubusercontent.com/110957364/189371617-2d01a690-c223-4aa9-9fcb-cc8ad7ef8650.png)

**Comment by poonbcw** [comment]
ไม่แน่ใจแห้ะ เพราะตอนนี่โหลดมันก็ไม่นานนะ

**Comment by AutsadaWiriya** [comment]
ได้ละใช้ Microsoft Edge โหลดไม่ได้เลย
![image](https://user-images.githubusercontent.com/110957364/189372827-6f254925-8fc6-4196-ba31-855c9f91f166.png)
Brave อันนี้โหลดไว

**Comment by ppetes** [comment]
![safeimagekit-pixel-art](https://user-images.githubusercontent.com/110958597/189679759-92f83654-a82e-4db1-99fd-1d1e84a2ccd2.png)

**Comment by ppetes** [comment]
ได้ป่ะ

**Comment by poonbcw** [comment]
![virus101](https://user-images.githubusercontent.com/110962501/189939870-c4be9c91-72dc-41b5-b2cc-c4460c4c676a.png)
![virus102](https://user-images.githubusercontent.com/110962501/189939896-9b2d5b29-81ef-414c-98b8-5af9c4202d2c.png)

**Comment by poonbcw** [comment]
![virus201](https://user-images.githubusercontent.com/110962501/189945765-cd740a53-1944-4756-b883-dd009195d3d1.png)
![virus202](https://user-images.githubusercontent.com/110962501/189945769-5527cc70-a4e2-4f54-a7e8-d90d0b5b1f13.png)

**Comment by poonbcw** [comment]
!
![stabO1_1](https://user-images.githubusercontent.com/110962501/190081472-3b4bf83d-3a58-4cd8-80ae-d5587b04fb37.png)
[alert_0](https://user-images.githubusercontent.com/110962501/190081234-b2620051-3a51-4d84-a5ad-9bdc934a032a.png)

**Comment by poonbcw** [comment]
![alert_0](https://user-images.githubusercontent.com/110962501/190081744-e6bdc291-d903-4974-a873-4167b7ccd957.png)

**Comment by poonbcw** [comment]
![virus301](https://user-images.githubusercontent.com/110962501/190890699-1d49c33c-81cd-45df-b274-9c8e6f63cfbb.png)
![virus302](https://user-images.githubusercontent.com/110962501/190890702-3bc9911a-b87f-4389-aa47-fe148265ac60.png)

**Comment by poonbcw** [comment]
![virus401](https://user-images.githubusercontent.com/110962501/190892430-2705b9fe-cf4b-4268-9cdd-cd9e5908e857.png)
![virus402](https://user-images.githubusercontent.com/110962501/190892431-825b22ee-aa2b-4924-8354-34b52b3c6f0f.png)

**Comment by AutsadaWiriya** [comment]
จะเอา Map ไหนเป็นตัวอะไร มีกี่ตัวอะ

**Comment by ppetes** [comment]
ด่าน1 มี2 ด่าน2,3 มี3 ด้าน 4,5,6 มี4 ด่าน7,8มี5 ประมาณนี้

**Comment by ppetes** [comment]
เรามีกี่ด่านนะ8ป่ะ

**Comment by AutsadaWiriya** [comment]
> ด่าน1 มี2 ด่าน2,3 มี3 ด้าน 4,5,6 มี4 ด่าน7,8มี5 ประมาณนี้
ตัวละครแต่ละแบบเลือดไม่เท่ากันด้วยนะ

**Comment by poonbcw** [comment]
![virus501](https://user-images.githubusercontent.com/110962501/190896585-c95ec428-2b91-47ed-9218-deb99f6c0b0c.png)
![virus502](https://user-images.githubusercontent.com/110962501/190896587-8afd7762-bd3e-4d46-a873-ef81f2b482ea.png)
