### ISSUE TITLE
รวมโค้ดทุกอย่างเข้าด้วยกัน

### ISSUE THREAD

**Issue by ppetes** [ppetes/-scratch-2#8]

**Comment by AutsadaWiriya** [comment]
![image](https://user-images.githubusercontent.com/110957364/191301454-312e8740-e206-41d5-9e6e-a4b1f8049fbe.png)
![image](https://user-images.githubusercontent.com/110957364/191301577-9ee3d443-b1a8-4dfe-9b7e-a03c8634951b.png)
![image](https://user-images.githubusercontent.com/110957364/191301698-3aa2c7b6-d6ee-4df5-8ddf-25a37e591019.png)
![image](https://user-images.githubusercontent.com/110957364/191301823-23d62176-2e6b-4899-924b-cada79d6824f.png)
![image](https://user-images.githubusercontent.com/110957364/191301952-d207ed11-e092-42ef-b7ae-d0b8b76c867f.png)
![image](https://user-images.githubusercontent.com/110957364/191302521-030c697c-6ab6-469c-b4f6-04d50b054462.png)
![image](https://user-images.githubusercontent.com/110957364/191302122-cd043a15-c259-4ad0-949d-5ec1fcca6d51.png)
![image](https://user-images.githubusercontent.com/110957364/191302193-c529f74d-fe9d-4f66-8395-1d3a78de1e6d.png)
![image](https://user-images.githubusercontent.com/110957364/191302642-aa965d96-ff63-407d-8eeb-3670bd28baa8.png)
![image](https://user-images.githubusercontent.com/110957364/191302870-f85a197b-8c4c-4d38-9eee-57e0b832068f.png)
![image](https://user-images.githubusercontent.com/110957364/191302989-7c87b76a-edc3-48cf-bae7-b1e3f49e6b9e.png)
![image](https://user-images.githubusercontent.com/110957364/191303149-077430ad-c543-45ef-b484-163121f901d2.png)
![image](https://user-images.githubusercontent.com/110957364/191303241-085a0bce-6463-4931-8e40-47afd28107b4.png)
![image](https://user-images.githubusercontent.com/110957364/191303346-2f70e4af-6071-431c-b713-e8beb154509c.png)
![image](https://user-images.githubusercontent.com/110957364/191303408-9be18180-b3be-475a-b4d4-fce48b04dce4.png)
![image](https://user-images.githubusercontent.com/110957364/191303567-3bd80aa9-2490-45db-af44-a35aeb2959ec.png)
![image](https://user-images.githubusercontent.com/110957364/191303669-36a16918-7c3b-4343-9453-1fa33bdc6765.png)
![image](https://user-images.githubusercontent.com/110957364/191303849-583527e1-426e-47e8-839b-374062aaff01.png)
![image](https://user-images.githubusercontent.com/110957364/191303909-e7ee2074-c178-40da-bcfb-0a45e0f133de.png)
![image](https://user-images.githubusercontent.com/110957364/191303990-0b5fc930-2050-45b8-8aad-114dd729140f.png)
![image](https://user-images.githubusercontent.com/110957364/191304064-692bc593-dba2-474f-a5b0-ffa74e13a114.png)
![image](https://user-images.githubusercontent.com/110957364/191304096-c620ef2a-dbe0-44fb-bf4b-d48f01195da8.png)
![image](https://user-images.githubusercontent.com/110957364/191304139-750f422e-d2f5-4e88-97f0-9373b10bc851.png)
![image](https://user-images.githubusercontent.com/110957364/191304207-0eedad52-15ee-4b98-bbfb-6772d412f61a.png)
![image](https://user-images.githubusercontent.com/110957364/191304243-687170a8-6191-40fe-a9fd-ab2b5af5f32d.png)
![image](https://user-images.githubusercontent.com/110957364/191304277-7de64693-6bc4-42ab-9e50-2fb0f9d7fb1f.png)
![image](https://user-images.githubusercontent.com/110957364/191304318-175c7f7b-6920-4ed9-bfbe-779d6bde6174.png)
